# Generated by Django 5.2.1 on 2025-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
